修复 UniqueConstraint 失效的问题
noneplugin/nonebot-plugin-session pull request #11
Opened 2023-09-07 05:16 UTC by he0119

应该是同样的问题。

https://github.com/he0119/nonebot-plugin-wordcloud/pull/122

2023-09-07 11:49 UTC, ssttkkl requested changes

2023-09-07 11:49 UTC, ssttkkl commented on nonebot_plugin_session/model.py
>          if commit:
用nested transaction写入的话，可以不需要考虑commit的值无脑写

2023-09-07 11:49 UTC, ssttkkl commented on nonebot_plugin_session/model.py
>          if commit:
```python
session_model = SessionModel(
            bot_id=session.bot_id,
            bot_type=session.bot_type,
            platform=session.platform,
            level=session.level,
            id1=session.id1 or "",
            id2=session.id2 or "",
            id3=session.id3 or "",
        )

        # 并发时可能会出现重复插入的情况
        try:
            async with db_session.begin_nested():
                session.add(session_model)
        except exc.IntegrityError:
            session_model = (await db_session.scalars(statement)).one()

        if commit:
            await db_session.commit()
            await nested.refresh(session_model)

        return session_model
```

2023-09-08 05:56 UTC, he0119 commented
该安排 pre-commit.ci 了（

2023-09-09 07:51 UTC, merged